### ISSUE TITLE
Font replacement is not successful in the HyperOS CN environment.

### ISSUE THREAD

**Issue by Unex3** [AndroPlus-org/magisk-module-koruri-font#2]
When I install the module, it only changes in some places.
For example, a page in Chrome or a clock in the status bar will work, but everything else will be MiSans.

Environment:
Redmi K70E
Xiaomi HyperOS 1.0.10.0.UNLCNXM
No other magisk modules installed.

**Comment by AndroPlus-org** [comment]
Can you share this file:
/system/etc/fonts.xml

I don't have HyperOS device now so I can't check, but maybe there's some changes in that file.

**Comment by Unex3** [comment]
I uploaded the file to GDrive.

https://drive.google.com/file/d/1--GL5uULMZoYGWuH3rDTc-Ge5jr_5QDV/view?usp=drivesdk

**Comment by AndroPlus-org** [comment]
OK, please test this one:
[magisk-module-koruri-font.zip](https://github.com/AndroPlus-org/magisk-module-koruri-font/files/14260889/magisk-module-koruri-font.zip)

**Comment by Unex3** [comment]
Installing the module did not replace the font.

**Comment by Unex3** [comment]
I can see MiSans being replaced by Koruri Font in Font Settings, but most other apps, Control Center, etc. use MiSans.

**Comment by AndroPlus-org** [comment]
hmm, I'll check after my device receives HyperOS update...

**Comment by AndroPlus-org** [comment]
It looks like HyperOS forces MiSansVF if theme font isn't applied, even if the module replaces MiSansVF.ttf.
I added workaround to apply font as theme font in v26.

**Comment by Unex3** [comment]
Font substitution was successful in my environment as well. Thank you for your response.
